# Generated by Django 5.0.2 on 2024-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('sexo', models.BooleanField()),
                ('particularidad', models.CharField(max_length=100)),
                ('fecha_desaparicion', models.DateTimeField()),
                ('lugar_desaparicion', models.CharField(max_length=100)),
                ('informacion_contacto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
