# Generated by Django 5.0.2 on 2024-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_perro_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_desaparicion',
            field=models.DateTimeField(help_text='Ingrese la fecha en el formato dd/mm/aaaa hh:mm'),
        ),
    ]
