# Generated by Django 5.0.2 on 2024-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_perro_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='fecha_desaparicion',
            new_name='fecha_de_desaparicion',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='informacion_contacto',
            new_name='lugar_de_desaparicion',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='lugar_desaparicion',
        ),
        migrations.AddField(
            model_name='perro',
            name='informacion_de_contacto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perro/'),
        ),
    ]
