# Generated by Django 5.0.2 on 2024-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=100)),
                ('fecha_de_desaparicion', models.DateTimeField(help_text='Ingrese la fecha en el formato dd/mm/aaaa hh:mm')),
                ('lugar_de_desaparicion', models.CharField(max_length=100)),
            ],
        ),
    ]
