# Generated by Django 5.0.2 on 2024-03-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='color',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='informacion_de_contacto',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='particularidad',
        ),
    ]
